### PR TITLE
Support for armv7 and android NDK r16

### PR DESCRIPTION
**Pull request by siriux**
Minimum changes to make it work on armv7 and NDK r16. It probably needs more testing and support for other versions/targets.

### CODE REVIEW

**Comment by siriux** [comment]
This is related with issues https://github.com/tomaka/android-rs-glue/issues/123 and https://github.com/tomaka/android-rs-glue/issues/163

**Comment by tomaka** [comment]
Thanks! I haven't tested it but the fix looks good.

**Comment by grovesNL** [comment]
@tomaka Do you think the crate could be updated with this fix, or does it need more testing first? The additional flags seem to benefit `arm-linux-androideabi` in my case at least

**Comment by tomaka** [comment]
@grovesNL Please open a pull request with a version bump in the Cargo.toml. Once merged it will automatically be published.

**Pull request merged**
