### PR TITLE
Implement wake_event_loop method for Android

### PR DESCRIPTION
**Pull request by MortimerGoro**
Implement wake_event_loop method. Required to implement WindowProxy on Glutin for Android. Tested on Servo for Android ;)

### CODE REVIEW

**Comment by MortimerGoro** [comment]
This is the PR I'll do to version of glutin used in servo when this one is merged: https://github.com/MortimerGoro/glutin/commit/87d291efc8b0af09961315d57d8bf273309d31ad

I'll submit the PR to glutin upstream too

**Comment by tomaka** [comment]
R+, will merge when travis passes.

**Comment by MortimerGoro** [comment]
Hi tomaka ¿Could you bump version and publish the crate? I need to merge the new version in Servo

**Comment by tomaka** [comment]
Please submit a PR that bumps the version and I'll merge and publish it.

**Pull request merged**
