### PR TITLE
Expose option for multiple build targets

### PR DESCRIPTION
**Pull request by davidhewitt**
I use genymotion as my android emulator, which runs x86 code and so needed the 'i686-linux-android' target. After realising I had to change the cargo-apk's source to build this I decided to submit a patch.

Possibly there was a reason this wasn't already exposed?

### CODE REVIEW

**Comment by tomaka** [comment]
The reason why the feature is unfortunately not exposed is here: https://github.com/davidhewitt/android-rs-glue/blob/f13e7db7a8b92e19ec8d3d8ef1949423ae8f4ff5/cargo-apk/src/build.rs#L265

Basically the `.java` file that is common to all targets is responsible for loading the shared libraries. But technically it is possible for different targets to have different libraries.

I don't know enough Java to know how that works.

If you want to solve that, it would be very nice. If you can't/don't want/any other reason, you can just put a `assert!(config.build_targets.len() <= 1);` somewhere and I'll accept the PR.

**Comment by davidhewitt** [comment]
Ah fair enough! Cool I'll take a look later in the week and see if I can find out anything useful. Thanks

**Comment by davidhewitt** [comment]
@tomaka I think I've got this working now; I had to move the build_java_src call to happen once after all the build targets have finished compiling.

The java code loops through the supported platform apis and then if it finds a match it fires System.loadLibrary calls for the appropriate libs.

I have a rather artificial hacked test project which I tested this against for i686-linux-android and arm-linux-androideabi where the native library is named differently according to the platform; if you'd like to see it I'm happy to make a repository for it, but I'm not sure you would want to - it's 💩!

**Comment by tomaka** [comment]
Looks good, thanks!

**Pull request merged**
