### PR TITLE
Use Rust's extern function variadic argument support

### PR DESCRIPTION
**Pull request by FuegoFro**
Taking advantage of Rust's built in ability to call variadic `extern` functions makes it much easier and cleaner to call Java methods and instantiate new Java objects via the `JNIEnv`.

An example usage then becomes:

```rust
((*(*jni_env).functions).NewObject)(jni_env, some_java_class, some_constructor_id, arg1, arg2, arg3);
```

### CODE REVIEW

**Comment by tomaka** [comment]
I didn't write this code, so I don't really know if that's correct.

I'll leave the PR open for a few days, and merge if no-one says a word.

**Comment by FuegoFro** [comment]
That's fair :) Also I just realized I should have mentioned that I tested the new versions of `NewObject`, `CallObjectMethod`, `CallIntMethod`, and `CallCharMethod` (with zero and non-zero number of arguments) on both a KitKat 4.4.4 and a Lollipop 5.1 device and they worked as expected.

**Comment by FuegoFro** [comment]
Ping on this, it'd be awesome to get merged in :)

**Comment by tomaka** [comment]
Oops

**Comment by FuegoFro** [comment]
Thank you!

**Pull request merged**
